name: ProjectTests

on: [push, pull_request]

jobs:
  TestProject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9.7

      - name: Install Depedencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          /opt/hostedtoolcache/Python/3.9.7/x64/bin/python -m pip install --upgrade pip
          sudo pip3 install numpy
          sudo pip install numpy
          sudo apt install python3-numpy
          sudo apt install python3-numpy3

      - name: Launch Subject Tests
        run: |
          ./306radiator 4 1 1 >> testResult
          ./306radiator 12 3 9 1 6 >> testResult
          ./306radiator 4 1 1 2 2 >> testResult
          ./306radiator 5 1 2 3 2 >> testResult
          ./306radiator 8 4 6 3 6 >> testResult

      - name: Launch Error Handling Test 1
        continue-on-error: true
        run: ./306radiator 1 1 1 1 >> testResult

      - name: Launch Error Handling Test 2
        continue-on-error: true
        run: ./306radiator 4 1 1 1 3 >> testResult

      - name: Launch Error Handling Test 3
        continue-on-error: true
        run: ./306radiator 4 1 3 1 1 >> testResult

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./testResult